USE [FastOrder];
GO
CREATE TABLE TB_TIPO_INTEGRACAO (
    COD_TIPO_INTEGRACAO INT IDENTITY(1,1),
    DESC_TIPO_INTEGRACAO varchar(255),
	PRIMARY KEY (COD_TIPO_INTEGRACAO)
);

INSERT INTO TB_TIPO_INTEGRACAO 
VALUES 
('Sem integração'),
('Ifood');

select * from TB_TIPO_INTEGRACAO