USE [FastOrder];
GO
CREATE TABLE TB_INTEGRATION_PRODUCT (
    ID_PRODUCT_FASTORDER INT,
	ID_EXTERNAL_PRODUCT INT,
	ID_INTEGRATION_TYPE INT,
	PRIMARY KEY (ID_PRODUCT_FASTORDER, ID_EXTERNAL_PRODUCT,ID_INTEGRATION_TYPE),
);

INSERT INTO TB_INTEGRATION_PRODUCT 
VALUES 
(1,101,1),
(2,102,1),
(3,103,1);

select * from TB_INTEGRATION_PRODUCT