CREATE TABLE TB_PRODUTO_INTEGRACAO (
    COD_PRODUTO_FASTORDER INT,
	COD_PRODUTO_EXTERNO INT,
	COD_INTEGRACAO INT,
	PRIMARY KEY (COD_PRODUTO_FASTORDER, COD_PRODUTO_EXTERNO),
	FOREIGN KEY (COD_PRODUTO_FASTORDER) REFERENCES TB_PRODUTO(COD_PROD),
	FOREIGN KEY (COD_INTEGRACAO) REFERENCES TB_TIPO_INTEGRACAO(COD_TIPO_INTEGRACAO)
);

INSERT INTO TB_PRODUTO_INTEGRACAO 
VALUES 
(1,101,1),
(2,102,1),
(3,103,1);

select * from TB_PRODUTO_INTEGRACAO