USE [FastOrder];
GO
CREATE TABLE TB_PRODUTO_INTEGRACAO (
    COD_PRODUTO_FASTORDER INT,
	COD_PRODUTO_EXTERNO INT,
	COD_TIPO_INTEGRACAO INT,
	PRIMARY KEY (COD_PRODUTO_FASTORDER, COD_PRODUTO_EXTERNO,COD_TIPO_INTEGRACAO),
	FOREIGN KEY (COD_PRODUTO_FASTORDER) REFERENCES TB_PRODUCT(COD_PRODUCT),
	FOREIGN KEY (COD_TIPO_INTEGRACAO) REFERENCES TB_TIPO_INTEGRACAO(COD_TIPO_INTEGRACAO)
);

INSERT INTO TB_PRODUTO_INTEGRACAO 
VALUES 
(1,101,1),
(2,102,1),
(3,103,1);

select * from TB_PRODUTO_INTEGRACAO