CREATE TABLE TB_STATUS_PEDIDO (
    COD_STATUS_PEDIDO INT IDENTITY(1,1),
    DESC_STATUS_PEDIDO varchar(255),
	PRIMARY KEY (COD_STATUS_PEDIDO)
);

INSERT INTO TB_STATUS_PEDIDO 
VALUES 
('Realizado'),
('Em preparação'),
('Pronto'),
('Finalizado');

select * from TB_STATUS_PEDIDO