CREATE TABLE TB_ITEM_PEDIDO (
	COD_PEDIDO INT,
	COD_ITEM_PEDIDO INT,
	COD_PRODUTO INT,
	QUANTIDADE INT,
	PRIMARY KEY (COD_PEDIDO,COD_ITEM_PEDIDO),
	FOREIGN KEY (COD_PRODUTO) REFERENCES TB_PRODUTO(COD_PRODUTO)

);

INSERT INTO TB_ITEM_PEDIDO 
VALUES 
(1,1,1,3),
(1,2,2,4),
(2,1,2,1),
(3,1,1,2),
(3,2,3,4);

select * from TB_ITEM_PEDIDO