USE [FastOrder];
GO
CREATE TABLE TB_ORDEM_ITEM (
	ID_ORDER INT,
	ID_ORDEM_ITEM INT,
	COD_PRODUCT INT,
	QUANTITY INT,
	PRIMARY KEY (ID_ORDER,ID_ORDEM_ITEM),
);

INSERT INTO TB_ORDEM_ITEM 
VALUES 
(1,1,1,3),
(1,2,2,4),
(2,1,2,1),
(3,1,1,2),
(3,2,3,4);

select * from TB_ORDEM_ITEM