USE FASTORDER
GO

DROP PROC CONSULTAR_PEDIDOS
CREATE PROC CONSULTAR_PEDIDOS
(
	@COD_PEDIDO INT = NULL,
	@COD_STATUS INT = NULL
)

AS

DECLARE @MYEXECSQL NVARCHAR(MAX);



SET @MYEXECSQL = N'SELECT PEDIDO.COD_PEDIDO,
       ITPEDIDO.COD_ITEM_PEDIDO,
	   ITPEDIDO.COD_PRODUTO,
	   PRODUTO.DESC_PRODUTO,
	   PEDIDO.RETIRADA,
	   STSPEDIDO.DESC_STATUS_PEDIDO,
	   INTEGRAPRODUTO.DESC_TIPO_INTEGRACAO	   
	   FROM TB_PEDIDO PEDIDO
	INNER JOIN TB_ITEM_PEDIDO ITPEDIDO
		ON PEDIDO.COD_PEDIDO = ITPEDIDO.COD_PEDIDO
	INNER JOIN TB_STATUS_PEDIDO STSPEDIDO
		ON PEDIDO.COD_STATUS_PEDIDO = STSPEDIDO.COD_STATUS_PEDIDO 
	INNER JOIN TB_PRODUTO PRODUTO
		ON ITPEDIDO.COD_PRODUTO = PRODUTO.COD_PRODUTO
	INNER JOIN TB_TIPO_INTEGRACAO INTEGRAPRODUTO
		ON PEDIDO.COD_TIPO_INTEGRACAO = INTEGRAPRODUTO.COD_TIPO_INTEGRACAO
	WHERE 1=1
	'
	IF @COD_PEDIDO IS NOT NULL
	BEGIN
	SET @MYEXECSQL = @MYEXECSQL + 'AND PEDIDO.COD_PEDIDO = ' + @COD_PEDIDO 
	END
	

EXECUTE SP_EXECUTESQL  @MYEXECSQL,@COD_PEDIDO