USE FASTORDER
GO
-- Create a table type to match your input parameters
CREATE TYPE ItensPedidos AS TABLE 
( COD_PEDIDO INT 
	,COD_ITEM_PEDIDO INT 
	,COD_PRODUTO INT 
	,QUANTIDADE INT  );
GO

IF EXISTS (SELECT 1 
			FROM SYS.OBJECTS
			WHERE OBJECT_ID = OBJECT_ID('PR_I_TB_ITEM_PEDIDO')
					AND TYPE IN ('P','PC'))
	DROP PROCEDURE PR_I_TB_ITEM_PEDIDO

GO

CREATE PROC PR_I_TB_ITEM_PEDIDO
(
	 @Values ItensPedidos READONLY
)

AS
BEGIN 

	INSERT INTO dbo.TB_ITEM_PEDIDO
			   (
				   COD_PEDIDO,
				   COD_ITEM_PEDIDO,
				   COD_PRODUTO,
				   QUANTIDADE
			   )
		SELECT 
             COD_PEDIDO, COD_ITEM_PEDIDO,COD_PRODUTO,QUANTIDADE
          FROM
             @Values

	END
GO

GRANT EXECUTE ON PR_I_TB_ITEM_PEDIDO TO PUBLIC
GO

