USE FASTORDER
GO

IF EXISTS (SELECT 1 
			FROM SYS.OBJECTS
			WHERE OBJECT_ID = OBJECT_ID('PR_I_TB_PEDIDO')
					AND TYPE IN ('P','PC'))
	DROP PROCEDURE PR_I_TB_PEDIDO

GO

CREATE PROC PR_I_TB_PEDIDO
(
	 @RETIRADA VARCHAR(1) = NULL
	,@COD_TIPO_INTEGRACAO INT = NULL
	,@COD_STATUS_PEDIDO INT = NULL
	,@RUA VARCHAR(255) = NULL
	,@BAIRRO VARCHAR(255) = NULL
	,@CEP VARCHAR(255) = NULL
	,@NUM_RESIDENCIA INT = NULL
	,@DADO_COMPLEMENTAR VARCHAR(255) = NULL
	,@NUM_CELULAR VARCHAR(15) = NULL
)

AS
BEGIN

	INSERT INTO dbo.TB_PEDIDO
			   (
					RETIRADA,
					COD_TIPO_INTEGRACAO,
					COD_STATUS_PEDIDO,
					RUA,
					BAIRRO,
					CEP,
					NUM_RESIDENCIA,
					DADO_COMPLEMENTAR,
					NUM_CELULAR
			   )
	VALUES
			   (
				   @RETIRADA,
				   @COD_TIPO_INTEGRACAO,
				   @COD_STATUS_PEDIDO,
				   @RUA,
				   @BAIRRO,
				   @CEP,
				   @NUM_RESIDENCIA,
				   @DADO_COMPLEMENTAR,
				   @NUM_CELULAR
			   )

	SELECT SCOPE_IDENTITY()
END
GO

GRANT EXECUTE ON PR_I_TB_PEDIDO TO PUBLIC
GO


