USE FASTORDER
GO

CREATE PROC PR_I_TB_PEDIDO
(
	 @RETIRADA VARCHAR(1) = NULL
	,@COD_TIPO_INTEGRACAO INT = NULL
	,@COD_STATUS_PEDIDO INT = NULL
	,@RUA VARCHAR(255) = NULL
	,@BAIRRO VARCHAR(255) = NULL
	,@CEP VARCHAR(255) = NULL
	,@NUM_RESIDENCIA INT = NULL
	,@DADO_COMPLEMENTAR VARCHAR(255) = NULL
	,@NUM_CELULAR VARCHAR(15) = NULL
)

AS

INSERT INTO dbo.TB_PEDIDO
           (
				RETIRADA,
				COD_TIPO_INTEGRACAO,
				COD_STATUS_PEDIDO,
				RUA,
				BAIRRO,
				CEP,
				NUM_RESIDENCIA,
				DADO_COMPLEMENTAR,
				NUM_CELULAR
		   )
     VALUES
           (
			   @RETIRADA,
			   @COD_TIPO_INTEGRACAO,
			   @COD_STATUS_PEDIDO,
			   @RUA,
			   @BAIRRO,
			   @CEP,
			   @NUM_RESIDENCIA,
			   @DADO_COMPLEMENTAR,
			   @NUM_CELULAR
		   )
GO

