USE FASTORDER
GO

IF EXISTS (SELECT 1 
			FROM SYS.OBJECTS
			WHERE OBJECT_ID = OBJECT_ID('PR_S_TB_PRODUTO_INTEGRACAO')
					AND TYPE IN ('P','PC'))
	DROP PROCEDURE PR_S_TB_PRODUTO_INTEGRACAO

GO

CREATE PROC PR_S_TB_PRODUTO_INTEGRACAO
(
	 @COD_TIPO_INTEGRACAO INT
)

AS
BEGIN 

	SELECT COD_PRODUTO_FASTORDER
      ,COD_PRODUTO_EXTERNO
    FROM dbo.TB_PRODUTO_INTEGRACAO
	WHERE COD_TIPO_INTEGRACAO = @COD_TIPO_INTEGRACAO

	END
GO

GRANT EXECUTE ON PR_S_TB_PRODUTO_INTEGRACAO TO PUBLIC
GO

