// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pedidos.Domain.EntidadesEF
{
    public partial class TbIntegrationProduct
    {
        public int IdProductFastorder { get; set; }
        public int IdExternalProduct { get; set; }
        public int? IdIntegrationType { get; set; }

    }
}