// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pedidos.Domain.EntidadesEF
{
    public partial class TbIntegrationType
    {
        public TbIntegrationType()
        {
            TbOrder = new HashSet<TbOrder>();
        }

        public int IdIntegrationType { get; set; }
        public string DescIntegrationType { get; set; }

        public virtual ICollection<TbOrder> TbOrder { get; set; }
    }
}