// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pedidos.Domain.EntidadesEF
{
    public partial class TbOrderStatus
    {
        public int IdOrderStatus { get; set; }
        public string DescOrderStatus { get; set; }

    }
}