// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pedidos.Domain.EntidadesEF
{
    public partial class TbOrderItem
    {
        public int IdOrder { get; set; }
        public int IdOrderItem { get; set; }
        public int? CodProduct { get; set; }
        public int? Quantity { get; set; }
    }
}