// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pedidos.Domain.EntidadesEF
{
    public partial class TbPedido
    {
        public int CodPedido { get; set; }
        public string Retirada { get; set; }
        public int? CodTipoIntegracao { get; set; }
        public int? CodStatusPedido { get; set; }
        public string Rua { get; set; }
        public string Bairro { get; set; }
        public string Cep { get; set; }
        public int? NumResidencia { get; set; }
        public string DadoComplementar { get; set; }
        public string NumCelular { get; set; }

        public virtual TbStatusPedido CodStatusPedidoNavigation { get; set; }
        public virtual TbTipoIntegracao CodTipoIntegracaoNavigation { get; set; }
    }
}