// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pedidos.Domain.EntidadesEF
{
    public partial class TbProdutoIntegracao
    {
        public int CodProdutoFastorder { get; set; }
        public int CodProdutoExterno { get; set; }
        public int? CodTipoIntegracao { get; set; }

        public virtual TbProduct CodProdutoFastorderNavigation { get; set; }
        public virtual TbTipoIntegracao CodTipoIntegracaoNavigation { get; set; }
    }
}