// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pedidos.Domain.EntidadesEF
{
    public partial class TbProduto
    {
        public TbProduto()
        {
            TbItemPedido = new HashSet<TbItemPedido>();
            TbProdutoIntegracao = new HashSet<TbProdutoIntegracao>();
        }

        public int CodProduto { get; set; }
        public string DescProduto { get; set; }
        public double? ValorProduto { get; set; }

        public virtual ICollection<TbItemPedido> TbItemPedido { get; set; }
        public virtual ICollection<TbProdutoIntegracao> TbProdutoIntegracao { get; set; }
    }
}