// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pedidos.Domain.EntidadesEF
{
    public partial class TbTipoIntegracao
    {
        public TbTipoIntegracao()
        {
            TbPedido = new HashSet<TbPedido>();
            TbProdutoIntegracao = new HashSet<TbProdutoIntegracao>();
        }

        public int CodTipoIntegracao { get; set; }
        public string DescTipoIntegracao { get; set; }

        public virtual ICollection<TbPedido> TbPedido { get; set; }
        public virtual ICollection<TbProdutoIntegracao> TbProdutoIntegracao { get; set; }
    }
}